### PR TITLE
fix(FR-1056): Use fetch-event-source for authenticated SSE requests

### LINKED ISSUE #3740: Support for custom headers in SSE using @microsoft/fetch-event-source
We are currently using Server-Sent Events (SSE) to track background tasks. However, the built-in EventSource in browsers does not allow specifying custom headers, which is necessary for authentication purposes. To address this limitation, we should consider using a package like @microsoft/fetch-event-source that supports custom headers.

[View original message posted by Gyubong Lee on 5/31/2025, 12:35:14 PM](https://teams.microsoft.com/l/message/19:c693c946ce4140c59f3819da0fbd00e7@thread.skype/1748666114382?parentMessageId=1748507367368)

JIRA Issue: FR-1056

### PR DESCRIPTION
**Pull request by ironAiken2**
Resolves #3740 ([FR-1056](https://lablup.atlassian.net/browse/FR-1056))

Currently, when accessing an endpoint on a remote server, the authentication cookie is not included in the request, making background task tracking impossible due to permissions issues.

By default, when you declare an SSE handler, you can declare a BaseType that will be common to all handlers.
```
const SSEEventHandlers: SSEEventHandlerTypes<BackgroundTaskEvent> = { ... } 
```
If you need a different type for a particular handler, you can override it by declaring the handler that requires type overriding next to the BaseType.
```
const SSEEventHandlers: SSEEventHandlerTypes<BackgroundTaskEvent, { onFailed: {message: {error: string}}}>
```

This PR fixes this by sending requests with the session ID in the request header so that authentication to the background task can be tracked properly.

**Changes:** 
- Instead of using the EventSource web api (EventSource does not support the ability to set custom headers), modify the request to include the authentication session ID in a custom header using microsoft's fetch-event-source library.

**How to test:**
- Set the remote server to endpoint and log in to webui.
- Perform a task that has a background task (e.g. rescan images, validate services, etc.)
- Verify that SSE is coming through.

**Checklist:** (if applicable)

- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

[FR-1056]: https://lablup.atlassian.net/browse/FR-1056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ironAiken2** [comment]
* **#3774** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3774?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3774?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=3774).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: react/src/helper/index.tsx [hunk 1]
```diff
@@ -610,3 +611,85 @@ export function getOS() {
   if (_.includes(userAgent, 'linux')) return 'Linux';
   return 'Linux';
 }
+
+export type SSEEventHandlers = {
+  onUpdated?: (data: any, controller?: AbortController) => void;
+  onDone?: (data: any) => void;
+  onFailed?: (data: any) => void;
+  onTaskFailed?: (data: any) => void;
+  onTaskCancelled?: (data: any) => void;
```
Comment (nowgnuesLee) [inline react/src/helper/index.tsx]: How about using `unknown` type instead of `any`?

File: react/src/helper/index.tsx [hunk 2]
```diff
@@ -610,3 +611,85 @@ export function getOS() {
...
+ * @returns
+ */
+export function listenToBackgroundTask(
+  taskID: string,
+  handlers: SSEEventHandlers,
+) {
+  const controller = new AbortController();
+  const signal = controller.signal;
+
+  const reqUrl = `/events/background-task?task_id=${taskID}`;
```
Comment (nowgnuesLee) [inline react/src/helper/index.tsx]: Please use `URLSearchParams`.

**Review by nowgnuesLee — CHANGES_REQUESTED** [review]

**Review by nowgnuesLee — APPROVED** [review]
LGTM

**Review by yomybaby — APPROVED** [review]
LGTM
