### PR TITLE
fix: Use `blockedMenuItem` to hide and show pipeline button

### LINKED ISSUE #2035: Remove hideSideMenuButton property and related statement to keep integrity of menu visibility.
### Main idea

Since we've been using "blocklist" in configuration to set visibility of menu in sidebar, I think it's better to remove `hideSideMenuButton` property, which only works for FastTrack link in the menu.

### Alternative ideas

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rapsealk**
This PR is a follow-up of #2020 and resolves #2035 by using `blockedMenuItem` to manage various menu buttons in a single point.

NOTE: Add `pipeline` to `[ui].menu_blocklist` from `webserver.conf` to hide, or it will be shown otherwise.

Refs
- #1938

**Checklist:** (if applicable)

- [x] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by lizable** [comment]
Let's add `hideList` as a new config setting and rename `blockList` to `disableList`. And It's better to apply `hideList` option to all menu in sidebar.

File: src/components/backend-ai-webui.ts [hunk 1]
```diff
@@ -451,6 +449,8 @@ export default class BackendAIWebUI extends connect(store)(LitElement) {
       this.blockedMenuItem = config.menu.blocklist
         .split(',')
         .map((x: string) => x.trim());
+      // Remove summary from accidentally added in config.menu.blocklist
+      this.blockedMenuItem.filter((menuTitle) => menuTitle !== 'summary');
```
Comment (lizable) [inline src/components/backend-ai-webui.ts:453]: Since fallback page is `summary`, we cannot block summary menu.

File: src/components/backend-ai-webui.ts [hunk 2]
```diff
@@ -1452,24 +1440,17 @@ export default class BackendAIWebUI extends connect(store)(LitElement) {
...
-              ? html`
+            <!--<mwc-list-item graphic="icon" ?selected="${this._page ===
+            'session'}" @click="${() =>
+              this._moveTo(
+                '/session',
+              )}" ?disabled="${this.inactiveMenuItem.includes('session')}">
+              <i class="fas fa-list-alt" slot="graphic" id="sessions-menu-icon"></i>
+              <span class="full-menu">${_t('webui.menu.Sessions')} new</span>
+            </mwc-list-item>-->
+            ${!this.supportServing || this.blockedMenuItem.includes('serving')
```
Comment (lizable) [inline src/components/backend-ai-webui.ts:1451]: I also set the visibility of serving page not only dependent to Core version supports but also checking whether `serving` menu is included to blocklist.

**Review by lizable — APPROVED** [review]
LGTM.
I also touched up the visibility of menu according to blocklist, except for `summary` menu. When user tries to access a wrong page(hidden page),[ there's a fallback page which provides "go back to summary"](https://github.com/lablup/backend.ai-webui/blob/3cd9bd3639577db480fe1adadc10cbc5d63cfca0/src/components/backend-ai-error-view.ts#L96). Therefore I added simple filter to exclude `summary` page from blocklist in case of input error by user.
