### PR TITLE
fix: ToS(Terms of Service) / Privacy Policy dialog disappears after closing one of them

### LINKED ISSUE #1123: ToS(Terms of Service) / Privacy Policy dialog disappears after closing one of them.
**Describe the bug**
문제가 발생하는 상황에 대한 요약 설명을 적어주세요.

When the user opens ToS or Privacy Policy dialog and closes by clicking `X` button in the right-top of the dialog and tries to open another one, then the dialog doesn't show up unless the user refreshes the page.

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:
> ⚠️ &nbsp; NOTICE:
> If you are using local development environment, then you need to enable `signupSupport` in configuration file first.
> Please check `config.toml` description in [README.md](https://github.com/lablup/backend.ai-webui#configuration).
1. Go to 'login' page.
2. Click on 'SIGN UP' button
3. Signup dialog appears.
4. Click `Terms of service` or `Privacy Policy` text at the bottom of the dialog, which is green colored.
5. `ToS` or `Privacy Policy` dialog shows up.
6. Click `X` button at the right-top of the dialog.
7.  Do the same step in step 4.
8. See the error.

**Expected behavior**
원래 기대했던 동작은 어떤 것인지 명확하게 적어주세요.
the dialog shows up after closing with `X` button.

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.
가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.
ToS-Privacy-Policy-dialog

**Client:**
 - OS: [e.g. macOS 10.14, Windows 10 (1903)]
 - App version: [e.g. 19.08.3] (if you are using a GUI client app)
 - Browser version: [e.g. Chrome 76, Safari, Edge] (if you are using a GUI web console)
 - Python version: [e.g. 3.7.4] (if you are using the Python SDK)
 - NodeJS version: [e.g. 12.0] (if you are using the Javascript SDK)

**Server:**
 - OS: [e.g. Ubuntu 18.04, CentOS 7.6, macOS 10.14]
   - Output of `uname -a`: [e.g. `Linux node01 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`]
 - Backend.AI version: [e.g. 19.09.0]
 - Python version: [e.g. 3.6.8]
 - Installation method: [e.g. on-premise, using cloud.backend.ai service, used scripts/install-dev.sh]

**Additional context**
추가적으로 문제 상황을 설명할 수 있는 다른 맥락을 기술해주세요.
🧩 Hint:
Clicking Dismiss button at the bottom of the dialog does also same action that `X` button does, but the different thing is that you can reopen the dialog after clicking "Dismiss" button, while clicking`X` button can't.
ToS-Privacy-Policy-dialog-hint

### PR DESCRIPTION
**Pull request by yujung7768903**
resolve #1123 
#### Problems

- [x] ToS(Terms of Service) / Privacy Policy dialog disappears after closing one of them
- [x] Scroll down, close the dialog, open it again. Then the scrollbar is in the middle.

* Before

https://user-images.githubusercontent.com/68562176/143206814-9910a9ef-e14f-4b74-814e-1dfbfd1de597.mov

* After

https://user-images.githubusercontent.com/68562176/143208448-88a561a8-b758-4125-8e5d-209822c93c41.mov

#### Cause
The TOS / PP dialog opens when the `show` variable of the "lablup-terms-of-service" element is false.
```
receiveTOSAgreement() {
    if (this.TOSdialog.show === false) {
      this.TOSdialog.tosContent = '';
      this.TOSdialog.tosLanguage = globalThis.backendaioptions.get('language');
      this.TOSdialog.title = _t('webui.menu.TermsOfService');
      this.TOSdialog.tosEntry = 'terms-of-service';
      this.TOSdialog.open();
    }
  }
```
Clicking dismiss button changes the `show` variable from true to **false** in the `close()` function of the "lablup-terms-of-service" element. However clicking x button doesn't change the variable.
```
close() {
    this.show = false;
    this._hideTOSdialog();
  }

_hideTOSdialog() {
    this.show = false;
    this.dialog.hide();
  }
```

So I add a CustomEvent so that the `close()` function can be called when users click the x button.

### CODE REVIEW

File: src/components/backend-ai-dialog.ts [hunk 1]
```diff
@@ -149,7 +149,12 @@ export default class BackendAiDialog extends LitElement {
    * Hide a dialog.
    */
   _hideDialog() {
-    this.hide();
+    if (this.dialog.parentNode.host.id === 'terms-of-service-dialog') {
```
Comment (lizable) [inline src/components/backend-ai-dialog.ts]: We already have a custom event trigger for the "closed" event in `backend-ai-dialog` component. Please refer to [this code](https://github.com/lablup/backend.ai-webui/blob/dd3e7aa1a5041773dd524ad2d4242d4f68c04f07/src/components/backend-ai-dialog.ts#L136-L141) and implement inside `lablup-terms-of-service`, instead of adding conditional codes in `backend-ai-dialog`.

**Review by lizable — CHANGES_REQUESTED** [review]
Please check the review below.

File: src/components/backend-ai-dialog.ts (hunk 1 above)
Comment (yujung7768903) [reply src/components/backend-ai-dialog.ts]: I remove tos-dialog-closing customEvent. Instead, I use `dialog-closed` event to invoke close() function inside `lablup-terms-of-service`

**Review by lizable — APPROVED** [review]
LGTM.

**Review by inureyes — APPROVED** [review]
LGTM
