### PR TITLE
fix(FR-2546): allow empty Full Name in account info validator

### LINKED ISSUE #6626: Full Name optional field shows validation error when empty in My Account Information modal
## Summary

The Full Name field in the "My Account Information" modal is labeled as (optional), but leaving it empty triggers a validation error: **"Full name should not exceed 64 characters"**.

## Root Cause

The validator in `UserProfileSettingModal.tsx` uses the condition `value && value.length < 65`, which is falsy when `value` is an empty string, causing it to fall through to `Promise.reject()`.

## Expected Behavior

An empty Full Name should pass validation since the field is optional.

## Suggested Fix

Change the validator condition to `!value || value.length < 65` to allow empty values.

—

Captured while working on branch: 04-10-fix_fr-2518_eliminate_blank_screen_between_splash_and_react_mount

JIRA Issue: FR-2546

### PR DESCRIPTION
**Pull request by nowgnuesLee**
Resolves #6626 (FR-2546)

## Summary
- Fixed an incorrect validator condition in the "My Account Information" modal that caused the optional Full Name field to show a validation error when left empty.
- The condition `value && value.length < 65` was falsy for empty strings, causing `Promise.reject()` to fire. Changed to `!value || value.length < 65` to allow empty values.

## Test plan
- [ ] Open "My Account Information" modal
- [ ] Leave Full Name empty and click Update — should succeed without validation error
- [ ] Enter a name under 64 chars — should pass
- [ ] Enter a name over 64 chars — should show the error message

## Verification
```
=== ALL PASS ===
```

### CODE REVIEW

**Comment by nowgnuesLee** [comment]
* **#6627** <a href="https://app.graphite.com/github/pr/lablup/backend.ai-webui/6627?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/lablup/backend.ai-webui/6627?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent changes, fast-track this PR to the front of the merge queue

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=6627).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: react/src/components/UserProfileSettingModal.tsx [hunk 1]
```diff
@@ -205,7 +205,7 @@ const UserProfileSettingModal: React.FC<Props> = ({
             rules={[
```
Comment (ironAiken2) [inline react/src/components/UserProfileSettingModal.tsx:205]: <p class='graphite__hidden'><i>[Re: line +204]</i></p>
The Korean translation is incorrect. It should be '성명'. This is because '사용자 이름 ' is a required field in the user creation and edit modal.
<p class='graphite__hidden'>See this comment inline on <a href="https://app.graphite.com/github/pr/lablup/backend.ai-webui/6627?utm_source=unchanged-line-comment">Graphite</a>.</p>

**Review by ironAiken2 — CHANGES_REQUESTED** [review]

File: react/src/components/UserProfileSettingModal.tsx (hunk 1 above)
Comment (nowgnuesLee) [reply react/src/components/UserProfileSettingModal.tsx:205]: Good point. Updated the Korean translations for `webui.menu.FullName`, `FullNameInvalid`, and `FullNameUpdated` to use '성명' instead of '사용자 이름' to disambiguate from the username field in the user creation/edit modal.

**Review by ironAiken2 — APPROVED** [review]
LGTM
