### PR TITLE
fix(FR-506): Set the width of the description in the session detail panel to maximum

### LINKED ISSUE #3142: Session info description width in session detail panel doesn't match with kernel list
{width=1608 height=1484}

JIRA Issue: FR-506

### PR DESCRIPTION
**Pull request by ironAiken2**
resolves #3142 (FR-506)

Fixes an issue where the design was inconsistent because the width of the description was not specified.

**Checklist:** (if applicable)

- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by ironAiken2** [comment]
* **#3143** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3143?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3143?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=3143).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: react/src/components/SessionDetailContent.tsx [hunk 1]
```diff
@@ -186,7 +186,7 @@ const SessionDetailContent: React.FC<{
           </Button.Group>
         </Flex>
 
-        <Descriptions bordered column={md ? 2 : 1}>
+        <Descriptions bordered column={md ? 2 : 1} style={{ width: '100%' }}>
```
Comment (yomybaby) [inline react/src/components/SessionDetailContent.tsx]: Is there any reason to set width instead of setting `align="stretch"` to parent Flex(line number 160)?

**Review by yomybaby — CHANGES_REQUESTED** [review]

File: react/src/components/SessionDetailContent.tsx (hunk 1 above)
Comment (ironAiken2) [reply react/src/components/SessionDetailContent.tsx]: I thought Flex in line 160 is for action button so I thought it didn't apply to description even though flex on line 149 had stretch set. I just Fixed.

**Review by yomybaby — APPROVED** [review]
LGTM
