### PR TITLE
fix(FR-2288): add resource group scoping alert to admin pending sessions page

### LINKED ISSUE #5922: Sessions stuck in pending state not visible in admin pending sessions page
Sessions created on the cluster (10.122.10.215) remain stuck in pending state indefinitely. However, these pending sessions are not visible in the admin pending sessions page (admin-session page), making it impossible for administrators to identify or manage them.

**Steps to Reproduce:**

1. Create a session on the cluster
1. Observe the session remains in pending state
1. Navigate to the admin pending sessions page
1. Session is not listed there

**Expected Behavior:**

Pending sessions should be visible in the admin pending sessions page.

**Actual Behavior:**

Sessions stuck in pending state are not visible in the admin pending sessions page.

Captured while working on branch: HEAD

JIRA Issue: FR-2288

### PR DESCRIPTION
**Pull request by agatha197**
Resolves #5922 ([FR-2288](https://lablup.atlassian.net/browse/FR-2288))

## Summary
- Add Alert component to `PendingSessionNodeList` indicating the view is filtered by the currently selected resource group
- Show info alert when a resource group is selected, warning alert when none is selected
- Replace `|| 'default'` fallback with `?? ''` to avoid silently querying a potentially non-existent resource group
- Add i18n keys for the new alert messages

## Files Changed
- `react/src/components/PendingSessionNodeList.tsx`
- `resources/i18n/en.json`

[FR-2288]: https://lablup.atlassian.net/browse/FR-2288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: react/src/components/PendingSessionNodeList.tsx [hunk 1]
```diff
@@ -4,7 +4,7 @@
  */
 import SessionNodes from './SessionNodes';
 import SharedResourceGroupSelectForCurrentProject from './SharedResourceGroupSelectForCurrentProject';
-import { Form } from 'antd';
+import { Alert, Form } from 'antd';
```
[the remark this answers is not in the document]
Comment (agatha197) [reply react/src/components/PendingSessionNodeList.tsx]: Fixed. Replaced antd Alert with BAIAlert from backend.ai-ui.

File: react/src/components/PendingSessionNodeList.tsx [hunk 2]
```diff
@@ -95,6 +95,19 @@ const PendingSessionNodeList: React.FC = () => {
...
+        <Alert
+          type="info"
+          showIcon
+          message={t('adminSession.PendingSessionsScopedToResourceGroup')}
+        />
+      ) : (
+        <Alert
+          type="warning"
+          showIcon
+          message={t('adminSession.SelectResourceGroupToViewPendingSessions')}
```
[the remark this answers is not in the document]
Comment (agatha197) [reply react/src/components/PendingSessionNodeList.tsx]: Fixed. Changed message prop to title prop per Ant Design v6 convention.

File: react/src/components/PendingSessionNodeList.tsx [hunk 3]
```diff
@@ -95,6 +95,19 @@ const PendingSessionNodeList: React.FC = () => {
...
+        />
+      )}
```
[the remark this answers is not in the document]
Comment (agatha197) [reply react/src/components/PendingSessionNodeList.tsx]: Fixed. Changed alert condition from currentResourceGroup to deferredCurrentResourceGroup to keep the UI consistent with what's actually being queried.

File: resources/i18n/en.json [hunk 4]
```diff
@@ -5,7 +5,9 @@
     "ActiveAgentsTooltip": "Shows an at-a-glance overview of all agents currently running in the system."
   },
   "adminSession": {
-    "PendingSessions": "Pending Sessions"
+    "PendingSessions": "Pending Sessions",
+    "PendingSessionsScopedToResourceGroup": "Showing pending sessions for the selected resource group only. Switch resource groups to view sessions in other groups.",
+    "SelectResourceGroupToViewPendingSessions": "Please select a resource group to view pending sessions."
```
[the remark this answers is not in the document]
Comment (agatha197) [reply resources/i18n/en.json]: Fixed. Added the new keys to all 20 non-English locale files (de, el, es, fi, fr, id, it, ja, ko, mn, ms, pl, pt-BR, pt, ru, th, tr, vi, zh-CN, zh-TW) using English strings as fallback.

File: react/src/components/PendingSessionNodeList.tsx [hunk 5]
```diff
@@ -52,7 +52,7 @@ const PendingSessionNodeList: React.FC = () => {
 
   const queryVariables: PendingSessionNodeListQuery$variables = useMemo(
     () => ({
-      resource_group_id: deferredCurrentResourceGroup || 'default',
+      resource_group_id: deferredCurrentResourceGroup ?? '',
       first: baiPaginationOption.first,
       offset: baiPaginationOption.offset,
     }),
```
[the remark this answers is not in the document]
Comment (agatha197) [reply react/src/components/PendingSessionNodeList.tsx:59]: The query with an empty string resource_group_id is intentional - the backend handles this case and returns an empty result, which is consistent with showing the warning alert when no resource group is selected. This avoids suspense flickering from conditionally rendering the query component.

**Review by nowgnuesLee — APPROVED** [review]
LGTM

File: react/src/components/PendingSessionNodeList.tsx [hunk 6]
```diff
@@ -95,6 +96,19 @@ const PendingSessionNodeList: React.FC = () => {
 
   return (
     <BAIFlex direction="column" align="stretch" gap="sm">
+      {deferredCurrentResourceGroup ? (
+        <BAIAlert
+          type="info"
+          showIcon
+          title={t('adminSession.PendingSessionsScopedToResourceGroup')}
```
Comment (ironAiken2) [inline react/src/components/PendingSessionNodeList.tsx]: Please use the description property.

File: react/src/components/PendingSessionNodeList.tsx [hunk 7]
```diff
@@ -95,6 +96,19 @@ const PendingSessionNodeList: React.FC = () => {
...
+        />
+      ) : (
+        <BAIAlert
+          type="warning"
+          showIcon
+          title={t('adminSession.SelectResourceGroupToViewPendingSessions')}
```
Comment (ironAiken2) [inline react/src/components/PendingSessionNodeList.tsx]: same as above

File: resources/i18n/de.json [hunk 8]
```diff
@@ -5,7 +5,9 @@
     "ActiveAgentsTooltip": "Zeigt einen Überblick auf einen Blick über alle im System ausgeführten Agenten."
   },
   "adminSession": {
-    "PendingSessions": "Ausstehende Sitzungen"
+    "PendingSessions": "Ausstehende Sitzungen",
+    "PendingSessionsScopedToResourceGroup": "Showing pending sessions for the selected resource group only. Switch resource groups to view sessions in other groups.",
+    "SelectResourceGroupToViewPendingSessions": "Please select a resource group to view pending sessions."
```
Comment (ironAiken2) [inline resources/i18n/de.json]: It appears that translations for both the PendingSessionsScopedToResourceGroup and SelectResourceGroupToViewPendingSessions keys have been provided in English.

File: react/src/components/PendingSessionNodeList.tsx (hunk 6 above)
Comment (ironAiken2) [reply react/src/components/PendingSessionNodeList.tsx]: Fixed. Changed to use `description` prop and simplified to always show `PendingSessionsScopedToResourceGroup` alert (removed the conditional based on `deferredCurrentResourceGroup`).

File: react/src/components/PendingSessionNodeList.tsx (hunk 7 above)
Comment (ironAiken2) [reply react/src/components/PendingSessionNodeList.tsx]: Fixed. Removed the second alert entirely — now only showing `PendingSessionsScopedToResourceGroup` with `description` prop.

File: resources/i18n/de.json (hunk 8 above)
Comment (ironAiken2) [reply resources/i18n/de.json]: Fixed. Added proper native translations for `PendingSessionsScopedToResourceGroup` in all 20 non-English locale files. Also removed the unused `SelectResourceGroupToViewPendingSessions` key from all locales.

**Review by ironAiken2 — APPROVED** [review]
LGTM
