### PR TITLE
fix(FR-1537): refactor file explorer to use prop-based permissions instead of GraphQL fragments

### LINKED ISSUE #4375: Error when accessing project folder after changing project to model store
## Impact

Users are unable to access the project folder after changing the project to a model store due to a validation error.

## Expected behavior

The system should allow access to the project folder without errors after changing the project to a model store.

## Actual behavior

An error message is displayed: "invalid type for variable: 'projectId'" with code "VALIDATION_INVALID_TYPE_VARIABLE".

## Steps to reproduce

- Change the project to a model store.
- Attempt to access the project folder.

## Environment

The environment details are not specified.

## Workarounds

No workarounds have been identified.

## Other information

The error message includes details about the variable 'projectId' being of an invalid type.

[View original message posted by Sujin Kim on 9/30/2025, 5:47:46 PM](https://teams.microsoft.com/l/message/19:14c484402d874dafb15806d093b95a82@thread.skype/1759222066404?parentMessageId=1759222066404)

JIRA Issue: FR-1537

### PR DESCRIPTION
**Pull request by ironAiken2**
resolves #4375 ([FR-1537](https://lablup.atlassian.net/browse/FR-1537))

### refactor file explorer to use prop-based permissions instead of GQL fragments

Resolves an issue where BAIFileExplorer fails to retrieve the project ID for the model_store project when using internal values from baiClient, preventing explorer usage. BAIFileExplorer now receives permissions via Prop and modifies the behavior so that permission checks are performed on the using side. 

**Checklist:** (if applicable)

- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

[FR-1537]: https://lablup.atlassian.net/browse/FR-1537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ironAiken2** [comment]
* **#4384** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/4384?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/4384?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=4384).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: react/src/components/FolderExplorer.tsx [hunk 1]
```diff
@@ -51,7 +56,16 @@ const FolderExplorer: React.FC<FolderExplorerProps> = ({
...
   const { uploadStatus, uploadFiles } = useFileUploadManager(vfolderID);
   const [fetchKey, updateFetchKey] = useFetchKey();
+  const baiClient = useSuspendedBackendaiClient();
+  const currentDomain = useCurrentDomainValue();
   const currentProject = useCurrentProjectValue();
+  const currentUserAccessKey = baiClient?._config?.accessKey;
+  const { unitedAllowedPermissionByVolume } =
+    useMergedAllowedStorageHostPermission(
+      currentDomain,
+      currentProject?.id,
```
Comment (yomybaby) [inline react/src/components/FolderExplorer.tsx]: you can remove `?.`

**Review by yomybaby — APPROVED** [review]
LGTM

**Review by nowgnuesLee — APPROVED** [review]
LGTM
