### PR TITLE
Show warning dialog and validation message when setting rate limit below 100

### LINKED ISSUE #1469: Show warning dialog when setting rate limit below 100
### Main idea

The rate limit function limits the number of API calls per 900 seconds to prevent unexpected DDoS attacks and API abuse. However, if this value is too small, API operations such as login using API calls will also be blocked. 

The rate limit value is also used to block spammers, so the setting can be as small as 1 as before, but when setting a value less than 100, let's improve the user interface to provide a warning and a dialog asking to continue.

### Alternative ideas

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Sujin-Kim1**
this resolves #1469 

[Screenshots]
- Input below 100
image

- Click the `SAVE CHANGES` button when the rate limit is below 100.
image

### CODE REVIEW

File: src/components/backend-ai-credential-list.ts [hunk 1]
```diff
@@ -696,25 +697,91 @@ export default class BackendAICredentialList extends BackendAIPage {
...
+
+  closeDialog(id) {
+    (this.shadowRoot?.querySelector('#' + id) as BackendAIDialog).hide();
+  }
+
   /**
    * Save a keypair modification.
    *
-   * @param {Event} e - Dispatches from the native input event each time the input changes.
+   * @param {boolean} confirm - Save keypair info even if rateLimit is less the warningRateLimit if `confirm` is true.
```
Comment (agatha197) [inline src/components/backend-ai-credential-list.ts:765]: When setting `closeWithConfirm` to `keypair-modify-dialog`, the `keypair-modify-dialog` cannot be closed immediately by pressing the close button. So I added confirm param to this function.

Comment (lizable) [reply src/components/backend-ai-credential-list.ts:765]: I'll check it.

Comment (agatha197) [reply src/components/backend-ai-credential-list.ts:765]: [backend-ai-credential-list.ts.zip](https://github.com/lablup/backend.ai-webui/files/9650443/backend-ai-credential-list.ts.zip)
this is the version of adding confirm dialog

File: src/components/backend-ai-credential-list.ts [hunk 2]
```diff
@@ -696,25 +697,91 @@ export default class BackendAICredentialList extends BackendAIPage {
       `, root);
   }
 
+  _validateRateLimit() {
```
Comment (lizable) [inline src/components/backend-ai-credential-list.ts:704]: I think we should use "[_addInputValidator](https://github.com/lablup/backend.ai-webui/blob/3ee743375ebe4fc26baa0a26d71a67394efbae7f/src/components/backend-ai-page.ts#L77-L126)" instead of adding custom validator in every components. Anyway let's handle them as a separate issue.

File: src/components/backend-ai-credential-list.ts [hunk 3]
```diff
@@ -889,7 +960,8 @@ export default class BackendAICredentialList extends BackendAIPage {
                 label="${_t('credential.RateLimit')}"
                 validationMessage="${_t('credential.RateLimitValidation')}"
                 helper="${_t('credential.RateLimitValidation')}"
-                @change=${() => this._adjustRateLimit()}
+                @change="${() => this._validateRateLimit()}"
```
Comment (lizable) [inline src/components/backend-ai-credential-list.ts:976]: Any reasons to add two event handlers (change, input) in here?

**Review by lizable — CHANGES_REQUESTED** [review]
I found one minor curiosity.

File: src/components/backend-ai-credential-list.ts (hunk 3 above)
Comment (agatha197) [reply src/components/backend-ai-credential-list.ts:976]: Now that I see it, I'll just need one.

File: src/components/backend-ai-credential-list.ts (hunk 2 above)
Comment (agatha197) [reply src/components/backend-ai-credential-list.ts:704]: I agree. It's better to be handled by https://github.com/lablup/backend.ai-webui/issues/1380.
