### PR TITLE
fix(FR-1778): Modified to open the terminal when the ‘Launch Terminal App’ button is clicked in the session detail panel

### LINKED ISSUE #4801: cannot run terminal app from session detail panel
{width=238}

manager 25.15 `10.122.12.108`
Nothing happens when I click this button.

JIRA Issue: FR-1778

### PR DESCRIPTION
**Pull request by nowgnuesLee**
resolves #4801 (FR-1778)

In this PR, I updated to conditionally skip `_openTerminalGuideDialog()`

**Checklist:** (if applicable)

- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by nowgnuesLee** [comment]
* **#4803** <a href="https://app.graphite.com/github/pr/lablup/backend.ai-webui/4803?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/lablup/backend.ai-webui/4803?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=4803).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by yomybaby — APPROVED** [review]
LGTM

File: src/components/backend-ai-app-launcher.ts [hunk 1]
```diff
@@ -1524,7 +1524,11 @@ export default class BackendAiAppLauncher extends BackendAIPage {
    */
   async runTerminal(sessionUuid: string) {
     const isVisible = localStorage.getItem('backendaiwebui.terminalguide');
-    if (!isVisible || isVisible === 'true') {
+    if (
+      (!globalThis.backendaiclient.supports('copy-on-terminal') &&
+        !isVisible) ||
+      isVisible === 'true'
+    ) {
```
Comment (ironAiken2) [inline src/components/backend-ai-app-launcher.ts:1531]: The copy-on-terminal check is validated within the _openTerminalGuideDialog function. Here, it seems the remaining execution is not performed due to the return below it. It would be better to move the validation of the hideTerminal setting in localStorage inside the _openTerminalGuideDialog function and remove the return statement.
