### PR TITLE
fix(FR-1755): fix service validation message parsing and increase timeout

### LINKED ISSUE #4742: Bgtask Response Not Received Properly in Model Service Validation API
We are experiencing an issue with the Model Service Validation API where the response for bgtask is not being received correctly. This is impacting our ability to validate models effectively.

JIRA Issue: FR-1755

### PR DESCRIPTION
**Pull request by ironAiken2**
Resolves #4742 ([FR-1755](https://lablup.atlassian.net/browse/FR-1755))  
  
Backend.AI PR [#7119](https://github.com/lablup/backend.ai/pull/7119)

## Summary

- Fix `BackgroundTaskEvent.message` type from object to string to match actual API response
- Add JSON parsing for message payload in all SSE event handlers (`onUpdated`, `onFailed`, `onTaskCancelled`, `onTaskFailed`)
- Increase validation timeout from 10 seconds to 60 seconds for better reliability
- Add early return handling for "Task started" message

## Test plan

- [ ] Test model service validation flow
- [ ] Verify SSE events are properly parsed and handled
- [ ] Confirm validation completes within the new 60s timeout
- [ ] Check error handling when validation fails

[FR-1755]: https://lablup.atlassian.net/browse/FR-1755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: react/src/components/ServiceValidationView.tsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ interface ServiceValidationModalProps {
 }
 type BackgroundTaskEvent = {
   task_id: string;
-  message: { event: string; session_id: string };
+  message: string;
   current_progress: number;
   total_progress: number;
 };
```
Comment (nowgnuesLee) [inline react/src/components/ServiceValidationView.tsx:37]: <p class='graphite__hidden'><i>[Re: lines +53 to +59]</i></p>
it seens we also need error handling for `get_logs`
<p class='graphite__hidden'>See this comment inline on <a href="https://app.graphite.com/github/pr/lablup/backend.ai-webui/4778?utm_source=unchanged-line-comment">Graphite</a>.</p>

**Review by nowgnuesLee — CHANGES_REQUESTED** [review]

File: react/src/components/ServiceValidationView.tsx (hunk 1 above)
Comment (ironAiken2) [reply react/src/components/ServiceValidationView.tsx:37]: Validation must occur regardless of the get_logs request. Therefore, we will modify the code to call get_logs only when the session is in the session_started or session_terminated state, preventing log retrieval without handling get_logs failures.

**Review by nowgnuesLee — APPROVED** [review]
LGTM
