### PR TITLE
fix(FR-242): show vfolder list based on delegated user

### LINKED ISSUE #3017: Let's add `max_pending_session_count`, `max_concurrent_sftp_sessions` to keypair resource policy.
Let’s add `max_pending_session_count`, `max_concurrent_sftp_sessions` to `KeypairResourcePolicyList` and `KeypairResourcePolicySettingModal`.

JIRA Issue: FR-360

### PR DESCRIPTION
**Pull request by ironAiken2**
resolves #3017 (FR-242)

> The ability to create a session by setting a Session Owner is not currently available. https://lablup.atlassian.net/browse/BA-414
> In this PR, I'm aiming to show the right vfolder list for the set session owner.

In the `VFolderTable` used by the session launcher, we are fetching the vfolder list via the REST API. Since the API provides the ability to filter the data based on owner email, use it to show the vfolder list based on the delegated owner email assigned by the session launcher.

**feature:**
- If owner is set in the session launcher, it will show a list of vfolders for that user.
- If a previously selected vfolder exists, all selections will be reset when the owner related settings are changed.

**Checklist:** (if applicable)

- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by ironAiken2** [comment]
* **#3070** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3070?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3070?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=3070).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: react/src/components/VFolderTable.tsx [hunk 1]
```diff
@@ -145,16 +145,34 @@ const VFolderTable: React.FC<VFolderTableProps> = ({
...
+          return key !== undefined;
+        })
+      : false);
+  const ownerEmail = isValidOwner ? ownerInfo.email : undefined;
+
+  useEffect(() => {
+    formInstance.setFieldsValue({ mounts: undefined, vfolderAliasMap: {} });
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+  }, [isValidOwner]);
+
```
Comment (yomybaby) [inline react/src/components/VFolderTable.tsx]: VFolderTable is not a Form.Item component. Therefore, it can be used outside of a Form. If you want to impose a condition based on a specific user's email, VFolderTable should receive the email as a prop. The email condition is an input of this Component.

**Review by yomybaby — CHANGES_REQUESTED** [review]

File: react/src/components/VFolderTable.tsx (hunk 1 above)
Comment (ironAiken2) [reply react/src/components/VFolderTable.tsx]: Modified the `VFolderTableFormItem` that wraps the VFolderTable in a Form.Item component to be responsible for getting the value for the email and validating it.

**Review by yomybaby — CHANGES_REQUESTED** [review]
Please resolve lint error:
```
/home/runner/work/backend.ai-webui/backend.ai-webui/react/src/App.tsx
Warning:   198:23  warning  't' is assigned a value but never used  @typescript-eslint/no-unused-vars

```

**Comment by ironAiken2** [comment]
Just fixed.

File: react/src/components/VFolderTableFormItem.tsx [hunk 2]
```diff
@@ -30,6 +30,22 @@ const VFolderTableFormItem: React.FC<VFolderTableFormItemProps> = ({
 }) => {
   const form = Form.useFormInstance();
   const { t } = useTranslation();
+
+  const ownerInfo = form.getFieldValue('owner');
```
Comment (yomybaby) [inline react/src/components/VFolderTableFormItem.tsx]: - `form.getFieldValue` does not guarantee triggering a re-render when the `owner` is changed.

**Review by yomybaby — CHANGES_REQUESTED** [review]
It's necessary to refactor overall related to the separation of concerns. Let's  discuss this end of the this week.

File: react/src/components/VFolderTableFormItem.tsx (hunk 2 above)
Comment (ironAiken2) [reply react/src/components/VFolderTableFormItem.tsx]: Changed the part that gets the owner information to be managed inside `VFolderTableFormItem.tsx`. Modified the dependency settings to determine if the owner information is valid when it is changed and, if valid, to initialize the existing assigned vfolder alias.

**Review by yomybaby — CHANGES_REQUESTED** [review]
[iShot_2025-03-26_11.14.53.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> ](https://app.graphite.dev/media/video/XqC2uNFuj0wg8I60sMUh/cf088b5e-7705-4222-8d31-01824885dd3f.mp4)

After setting owner in the first step of session launcher. I couldn't select a vfolder. It's unselected automatically.

**Comment by ironAiken2** [comment]
When the VFolderList is changed by the owner, an initialization of aliasMap and mounts is required.

I changed it to reset the above values when the OwnerInfo changes in the `SessionOwnerSetterCard` component, but I don't like touching the vfolder side of the SessionOwner component interest. If you have any better ideas, please advise. @yomybaby

**Review by agatha197 — CHANGES_REQUESTED** [review]
automount folder still remains.

File: react/src/components/SessionOwnerSetterCard.tsx [hunk 3]
```diff
@@ -22,7 +22,7 @@
 import graphql from 'babel-plugin-relay/macro';
 import _ from 'lodash';
 import { CheckIcon } from 'lucide-react';
-import React, { Suspense, useState } from 'react';
+import React, { Suspense, useEffect, useState } from 'react';
```
Comment (agatha197) [inline react/src/components/SessionOwnerSetterCard.tsx]:
```suggestion
import React, { Suspense, useState } from 'react';
```

**Review by agatha197 — CHANGES_REQUESTED** [review]

**Review by yomybaby — APPROVED** [review]
LGTM

**Review by agatha197 — APPROVED** [review]
LGTM
