### PR TITLE
hotfix(FR-618): use Grid component instead of BAIBoard to fix broken layout in Electron

### LINKED ISSUE #3298: hotifx: Broken BAIBoard layout in Electron app

### PR DESCRIPTION
**Pull request by yomybaby**
Resolves #3298 (FR-618)

The BAIBoard displayed a broken UI in the Electron environment. To fix this, the draggable BAIBoard component has been replaced with a fixed grid layout on the StartPage. The new layout uses Ant Design's Row and Col components to create a responsive grid system that adapts to different screen sizes:
- Small screens: 1 card per row
- Medium screens: 2 cards per row
- Large screens: 4 cards per row

Each action item is now displayed in a fixed-height Card component, maintaining consistent spacing and alignment across the page.

### CODE REVIEW

**Comment by yomybaby** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3295?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3296** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3296?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3295** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3295?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3295?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#3294** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3294?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=3295).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: react/src/pages/StartPage.tsx [hunk 1]
```diff
@@ -2,6 +2,7 @@ import ActionItemContent from '../components/ActionItemContent';
 import BAIBoard, { BAIBoardItem } from '../components/BAIBoard';
```
Comment (ironAiken2) [inline react/src/pages/StartPage.tsx]:
```suggestion
// import BAIBoard, { BAIBoardItem } from '../components/BAIBoard';
```

File: react/src/pages/StartPage.tsx [hunk 2]
```diff
@@ -2,6 +2,7 @@ import ActionItemContent from '../components/ActionItemContent';
...
 import FolderCreateModal from '../components/FolderCreateModal';
 import ThemeSecondaryProvider from '../components/ThemeSecondaryProvider';
+import { filterEmptyItem } from '../helper';
 import { useSuspendedBackendaiClient, useWebUINavigate } from '../hooks';
 import { useBAISettingUserState } from '../hooks/useBAISetting';
```
Comment (ironAiken2) [inline react/src/pages/StartPage.tsx]:
```suggestion
// import { useBAISettingUserState } from '../hooks/useBAISetting';
```

**Review by ironAiken2 — CHANGES_REQUESTED** [review]
Card sizes are inconsistent on small screen sizes. And I left a few comments.

**Comment by yomybaby** [comment]
Thank you for your comment. To fix it, I set to `xs` value because it's a default value.

**Review by ironAiken2 — APPROVED** [review]
LGTM
