### PR TITLE
fix(FR-453): UserDropdownMenu isn't opening

### LINKED ISSUE #3083: The UserDropdownMenu isn't opening
After Ant.d upgraded, the UserdropdonwMenu doesn’t work properly.

JIRA Issue: FR-453

### PR DESCRIPTION
**Pull request by yomybaby**
resolves #3083 (FR-453)

Fixed a dropdown menu bug in the user profile button by wrapping the button content in a `div` element. This resolves an issue with the dropdown functionality when using `ReverseThemeProvider` in the current Ant Design version.

The fix removes the manual open state management that was previously implemented, allowing the dropdown to use its default behavior while maintaining proper functionality.

### CODE REVIEW

**Comment by yomybaby** [comment]
* **#3085** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3085?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3085?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=3085).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by agatha197 — APPROVED** [review]
LGTM

File: react/src/components/UserDropdownMenu.tsx [hunk 1]
```diff
@@ -181,45 +180,42 @@ const UserDropdownMenu: React.FC<{
...
-                  // border: 1,
-                  backgroundColor: token.colorBgBase,
-                }}
-              ></Avatar>
-            }
-          >
-            {screens.lg && _.truncate(userInfo.username, { length: 30 })}
-          </Button>,
-        )}
+        {/* Add a `div` to fix the Dropdown bug when the child is a `ReverseThemeProvider`. It might be related to the Ant Design version. */}
```
Comment (ragingwind) [inline react/src/components/UserDropdownMenu.tsx]: I think It would good to move this comment to Github issues for tracking. one of another reason is that we couldn't pretty sure that it is related to the ant-d problem as you mentioned in the comment

Comment (yomybaby) [reply react/src/components/UserDropdownMenu.tsx]: Thank you for the suggestion. I moved the `div` from `UserDropdownMenu` to `WebUIHeader` and changed the comment because it is more related to `ReverseThemeProvider` in DropDown (ConfigProvider).

**Review by ragingwind — APPROVED** [review]
