### PR TITLE
fix(FR-382, FR-384): Handle deprecated image name fields in service launcher and image download

### LINKED ISSUE #3043: Problem occurs with installing a new image
Image installation fails. The same as creating the model service, you get an error that the image is not found. Again, validation in a different environment is required.

### PR DESCRIPTION
**Pull request by ironAiken2**
resolves #3043 (FR-384) #3044 (FR-382)

Introduces a new `namespace` field for image objects while deprecating the existing `name` field. This change affects how image names are constructed throughout the application, particularly in the image installation modal, service launcher, and endpoint detail pages.

The image name construction now prioritizes the `namespace` field, falling back to `name` when namespace is not available: `registry/namespace:tag` or `registry/name:tag`.

**Checklist:**
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by ironAiken2** [comment]
* **#3042** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3042?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3042?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=3042).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: react/src/components/ServiceLauncherPageContent.tsx [hunk 1]
```diff
@@ -256,7 +257,7 @@ const ServiceLauncherPageContent: React.FC<ServiceLauncherPageContentProps> = ({
     return {
       image: (isManualImageEnabled
         ? formInput.environments.manual?.split('@')[0]
-        : `${formInput.environments.image?.registry}/${formInput.environments.image?.name}:${formInput.environments.image?.tag}`) as string,
+        : `${formInput.environments.image?.registry}/${formInput.environments.image?.namespace ?? formInput.environments.image?.name}:${formInput.environments.image?.tag}`) as string,
```
Comment (yomybaby) [inline react/src/components/ServiceLauncherPageContent.tsx]: It's the same as below. We don't need to generate the full image name. It already exists in ResourceAllocationFormItems.
```suggestion
        : formInput.environments.version.split('@')[0]) as string,
```

**Review by yomybaby — CHANGES_REQUESTED** [review]
