### PR TITLE
fix(FR-1680): redirect from the root page to the start page is not working

### LINKED ISSUE #4641: Redirect from the root page to the start page is not working
JIRA Issue: FR-1680

### PR DESCRIPTION
**Pull request by nowgnuesLee**
resolves #4641 (FR-1680)

This PR removes the Import & Run page and its corresponding menu item from the WebUI. The changes include:

1. Removing the `ImportAndRunPage.tsx` component
2. Removing the `import` menu key from the `MenuKeys` type
3. Removing the Import & Run menu item from the sidebar
4. Removing the `BAIExampleStartIcon` import that was only used for this page
5. Adding a redirect to the start page when the current page is 'start'

**Checklist:** (if applicable)

- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

File: src/components/backend-ai-webui.ts [hunk 1]
```diff
@@ -641,6 +641,9 @@ export default class BackendAIWebUI extends connect(store)(LitElement) {
       },
     ];
 
+    if (this._page === 'start') {
+      this._moveTo('/start');
+    }
```
Comment (yomybaby) [inline src/components/backend-ai-webui.ts]: The search params are being stripped out at this point.  
When accessing the app with a URL like the following, the import modal should open automatically:

http://127.0.0.1:9081/start?type=url&data=%7B%22url%22%3A%22https%3A%2F%2Fgithub.com%2Fhephaex%2Fdeeplearning-note%2Fblob%2Fmaster%2F08_dimensiolity_reduction.ipynb%22%7D

Comment (nowgnuesLee) [reply src/components/backend-ai-webui.ts]: I applied it and added some comments.

**Review by yomybaby — APPROVED** [review]
LGTM
