### PR TITLE
fix: show antd error message when failed to terminate in-service model

### LINKED ISSUE #2154: Let's Make an error message visible in the UI when deleting a service model
### Main idea

If you delete a model that is in service, the console only shows an error message. Let's show the error message in the UI for the user.

### Alternative ideas

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ironAiken2**
This PR resolves #2154 

Introduces
- set mutation Error type to access the error message
- show error message by using antd message

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

File: react/src/pages/ServingListPage.tsx [hunk 1]
```diff
@@ -492,7 +497,15 @@ const ServingListPage: React.FC<PropsWithChildren> = ({ children }) => {
...
             onError: (err) => {
-              console.log('terminateModelServiceMutation Error', err);
+              if (err?.message) {
+                message.error(
+                  _.truncate(err?.message, {
+                    length: 200,
+                  }),
+                );
+              } else {
+                message.error(t('modelService.FailedToTerminateService'));
```
Comment (yomybaby) [inline react/src/pages/ServingListPage.tsx:507]: Did you forget to submit `modelService.FailedToTerminateService` values?

**Review by yomybaby — CHANGES_REQUESTED** [review]

**Review by yomybaby — APPROVED** [review]

**Review by yomybaby — APPROVED** [review]
LGTM
