### PR TITLE
fix(FR-1486): correct plugin import path from relative to parent directory

### LINKED ISSUE #4294: Incorrect Import Path Errors When Applying Plugin Page in WebUI
When attempting to apply the plugin page in WebUI, an error occurs in the console due to an incorrect import path. This issue prevents the proper functionality of the plugin and needs to be addressed to ensure seamless integration.

**Steps to Reproduce:**

1. Navigate to the plugin page in WebUI.
1. Attempt to apply the plugin.
1. Observe the console for error messages related to import paths.

JIRA Issue: FR-1486

### PR DESCRIPTION
**Pull request by ironAiken2**
Resolves #4294 ([FR-1486](https://lablup.atlassian.net/browse/FR-1486))

## Changes
- Fixed plugin import path in `backend-ai-app.ts` to conditionally use the correct path based on environment
- Added dynamic NODE_ENV injection for development environment in `index.html`
- Removed hardcoded `process.env` from `index.html` and moved it to be injected during development
- Implemented template content replacement in `craco.config.js` to inject development environment variables

## How to test
- Run the application in development mode and verify plugins load correctly
- Build the application and verify plugins load correctly in production mode
- Check console for any plugin loading errors in both environments

This change ensures plugins are loaded from the correct path in both development and production environments, preventing console errors during plugin loading.

[FR-1486]: https://lablup.atlassian.net/browse/FR-1486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ironAiken2** [comment]
* **#4298** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/4298?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/4298?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=4298).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by agatha197 — CHANGES_REQUESTED** [review]
when I tested it, it occurs import error and original version is correct.

**Review by agatha197 — APPROVED** [review]
LGTM

File: src/backend-ai-app.ts [hunk 1]
```diff
@@ -129,7 +129,11 @@ const loadPage =
         if (typeof globalThis.backendaiPages !== 'undefined') {
           for (const item of globalThis.backendaiPages) {
             if ('url' in item) {
-              import('./plugins/' + item.url + '.js');
+              const path =
+                process.env.NODE_ENV === 'development'
```
Comment (yomybaby) [inline src/backend-ai-app.ts:133]: In the production build, `process` does not exist. Please check it if not already.

**Review by yomybaby — APPROVED** [review]
LGTM
