### PR TITLE
fix(FR-867): incorrect permission value display for 'wd' permission

### LINKED ISSUE #3534: Incorrect permission value display for a VFolder with `write-delete` permission
The VFolder write-delete (wd) permission is directly displayed as 'wd', even though there is no 'wd' option in the checkbox. However, when copying a model card, it can be copied with wd permission. Investigate this behavior and ensure consistency in permission display and functionality.

[View original message posted by Gyubong Lee on 2025. 4. 17. 오후 9:19:41](https://teams.microsoft.com/l/message/19:14c484402d874dafb15806d093b95a82@thread.skype/1744892381830?parentMessageId=1744892381830)

JIRA Issue: FR-867

### PR DESCRIPTION
**Pull request by agatha197**
Resolves #3534 ([FR-867](https://lablup.atlassian.net/browse/FR-867))

# Remove 'wd' permission option from folder permissions

This PR removes the 'wd' (write-delete) permission option from folder permissions throughout the application:

1. Updates `LegacyFolderExplorer.tsx` to handle 'wd' permission by converting it to 'rw' in the UI
2. Removes the 'Delete' permission option from the ModelCloneModal dropdown
3. Updates documentation in backend.ai-client-esm.ts to reflect that only 'ro' and 'rw' permissions are valid options

### Specific setting for review
1. update folder permission to 'wd' in DB.
```
update vfolders set permission='wd' where name='<vfolder name>';
```
2. check vfolder explorer

**Checklist:**

- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

[FR-867]: https://lablup.atlassian.net/browse/FR-867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by agatha197** [comment]
* **#3550** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3550?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3550?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=3550).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: react/src/components/LegacyFolderExplorer.tsx [hunk 1]
```diff
@@ -191,7 +193,7 @@ const LegacyFolderExplorer: React.FC<LegacyFolderExplorerProps> = ({
             {vfolder_node?.user === currentUser.uuid && (
               <BAISelect
                 tooltip={t('data.folders.MountPermission')}
-                defaultValue={vfolder_node?.permission || vfolder?.permission}
+                defaultValue={permission === 'wd' ? 'rw' : permission}
```
Comment (jopemachine) [inline react/src/components/LegacyFolderExplorer.tsx:196]: How about logging warning message when `wd` value is received, if the wd permission is not allowed here?

Also, I think rather than changing the permission to `rw`, it seems better to keep the permission as is and change the display format of `wd` to `ReadWrite`.

Comment (agatha197) [reply react/src/components/LegacyFolderExplorer.tsx:196]: I'll add a warning message. And if I keep the permission and change the display format of `wd`, it will be shown as below. So I'll leave as it is.
image

**Review by jopemachine — APPROVED** [review]
