### PR TITLE
fix(FR-894): show image commit error message

### LINKED ISSUE #3570: Fix missing error popup on session image commit in Neo session list
When committing a session image in the Neo session list, a 400 error occurs, but the error message popup does not appear. In contrast, the error message popup works correctly in the classic session list.

[View original message posted by Gyubong Lee on 2025. 4. 16. 오후 12:47:42](https://teams.microsoft.com/l/message/19:14c484402d874dafb15806d093b95a82@thread.skype/1744775262261?parentMessageId=1744775262261)

JIRA Issue: FR-894

### PR DESCRIPTION
**Pull request by ironAiken2**
resolves #3570 (FR-894)

### Improved Error Handling for Container Commit Modal

This PR enhances the error handling in the Container Commit Modal by:

1. Improving the notification system when container commit fails:
   - Added proper error notification with link to error logs
   - Added a "See error" button that redirects to the user settings logs tab

2. Reorganized code structure in ContainerCommitModal.tsx:
   - Reordered variable declarations for better readability
   - Added missing notification properties for consistency
   - Fixed error handling to properly display error messages

3. Added "SeeErrorLogs" translation string to all language files

These changes provide users with better feedback when container commit operations fail, making it easier to troubleshoot issues.

**Checklist:**

- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by ironAiken2** [comment]
* **#3580** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3580?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3580?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=3580).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: react/src/components/ComputeSessionNodeItems/ContainerCommitModal.tsx [hunk 1]
```diff
@@ -54,34 +53,40 @@ const ContainerCommitModal: React.FC<ContainerCommitModalProps> = ({
...
-            }
+            upsertNotification({
+              open: true,
+              type: 'error',
+              key: 'commitSession:' + session?.name,
+              message: 'commitSession: ' + session?.name,
+              description: err?.message,
+              toText: t('button.SeeErrorLogs'),
+              to: `/usersettings?tab=logs`,
+            });
```
Comment (nowgnuesLee) [inline react/src/components/ComputeSessionNodeItems/ContainerCommitModal.tsx]: You can use `upsertNotification` like this way.
```
   upsertNotification({
          message: 'commitSession: ' + session?.name,
          open: true,
          backgroundTask: {
            status: 'pending',
            promise: baiClient.computeSession.convertSessionToImage(
              session?.name ?? '',
              values.imageName,
            ),
            onChange: {
              resolved: ({ task_id }: any) => {
                onRequestClose();
                return {
                  backgroundTask: {
                    status: 'pending',
                    taskId: task_id,
                    promise: null,
                    percent: 0,
                    onChange: {
                      pending: t('session.CommitOnGoing'),
                      resolved: t('session.CommitFinished'),
                      rejected: t('session.CommitFailed'),
                    },
                  },
                };
              },
              rejected: (err: any) => {
                return {
                  open: true,
                  type: 'error',
                  message: 'commitSession: ' + session?.name,
                  description: err?.message,
                  toText: t('button.SeeErrorLogs'),
                  to: `/usersettings?tab=logs`,
                };
              },
            },
          },
        });
```

File: react/src/components/ComputeSessionNodeItems/ContainerCommitModal.tsx [hunk 2]
```diff
@@ -54,34 +53,40 @@ const ContainerCommitModal: React.FC<ContainerCommitModalProps> = ({
...
           })
           .finally(() => {
             setIsConfirmLoading(false);
           });
       })
       .catch((err) => {
-        console.log(err);
+        setIsConfirmLoading(false);
       });
```
Comment (nowgnuesLee) [inline react/src/components/ComputeSessionNodeItems/ContainerCommitModal.tsx]: How about using `finally` instead of `catch` if you don't use `err`

**Review by nowgnuesLee — CHANGES_REQUESTED** [review]

File: react/src/components/ComputeSessionNodeItems/ContainerCommitModal.tsx (hunk 2 above)
Comment (ironAiken2) [reply react/src/components/ComputeSessionNodeItems/ContainerCommitModal.tsx]: That `catch` is for valiating form items inputs, not for validating the APIs.

File: react/src/components/ComputeSessionNodeItems/ContainerCommitModal.tsx (hunk 1 above)
Comment (ironAiken2) [reply react/src/components/ComputeSessionNodeItems/ContainerCommitModal.tsx]: The sesison commit consists of getting a bgTask id for session creation via `baiClient.computeSession.convertSessionToImage` and tracking that task via notifications.

The catch statement above is a catch when the bgTask id is not fetched, and the error that occurs during the execution of the bg task should be modified to show the error in rejected as @nowgnuesLee said.

Comment (ironAiken2) [reply react/src/components/ComputeSessionNodeItems/ContainerCommitModal.tsx]: Getting the task id can be handled at once through the promise of upsertNotification, so I will fix that part as well.

**Review by nowgnuesLee — APPROVED** [review]
LGTM
