### PR TITLE
fix(FR-1470): preserve board items order after drag and drop

### LINKED ISSUE #4277: Board items cannot be moved in the narrow view of the Dashboard Page.
## Expected behavior

When a user drags and drops an item, the item should remain in the new location and not revert back to its original position.

## Actual behavior

After dragging and dropping an item, it reverts back to its original position, undoing the user's action.

[View original message posted by HyeokJin Kim on 9/15/2025, 1:03:09 PM](https://teams.microsoft.com/l/message/19:14c484402d874dafb15806d093b95a82@thread.skype/1757908989115?parentMessageId=1756284324858)

JIRA Issue: FR-1470

### PR DESCRIPTION
**Pull request by ironAiken2**
Resolves #4277 ([FR-1470](https://lablup.atlassian.net/browse/FR-1470))

## Summary

This PR fixes the issue where board items on Dashboard and Start pages revert to their original positions after drag & drop operations. Users can now properly rearrange board items and the layout will be preserved across page refreshes.

### DashboardPage.tsx
- Added useMemo optimization for mergedBoardItems calculation
- Implemented localStorage order preservation using Map-based sorting
- Import fix: Added useMemo to React imports

### StartPage.tsx  
- Refactored board items logic to match DashboardPage pattern
- Replaced state-based approach with useMemo and direct localStorage integration
- Removed unnecessary boardItems state and setBoardItems calls
- Improved performance by eliminating redundant re-renders

## Technical Implementation

The key fix involves sorting merged items by localStorage order while preserving new items:

1. Map initialBoardItems with localStorage data
2. Create order map from localStorage indices  
3. Sort merged items using localStorage order
4. New items get MAX_VALUE (placed at end)

## Impact

- Fixed: Board items now maintain their position after drag & drop
- Performance: Optimized with useMemo to prevent unnecessary recalculations  
- Backward compatibility: New items automatically appear at the end
- Consistency: Both Dashboard and Start pages use the same pattern

## Test Case

1. Go to Dashboard or Start page
2. Drag and drop any board item to a new position
3. Refresh the page
4. Expected: Item remains in the new position
5. Before this fix: Item would revert to original position

[FR-1470]: https://lablup.atlassian.net/browse/FR-1470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ironAiken2** [comment]
* **#4287** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/4287?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/4287?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=4287).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: react/src/pages/DashboardPage.tsx [hunk 1]
```diff
@@ -177,22 +177,36 @@ const DashboardPage: React.FC = () => {
...
+
+      mergedBoardItems.sort((a, b) => {
+        const aOrder = orderMap.get(a.id) ?? Number.MAX_VALUE;
+        const bOrder = orderMap.get(b.id) ?? Number.MAX_VALUE;
+        return aOrder - bOrder;
+      });
+    }
+
+    return filterOutEmpty(mergedBoardItems);
+  }, [initialBoardItems, localStorageBoardItems]);
```
Comment (nowgnuesLee) [inline react/src/pages/DashboardPage.tsx]: Since initialBoardItems and localStorageBoardItems are objects, useMemo will recalculate them anyway, so it isn’t necessary.

File: react/src/pages/StartPage.tsx [hunk 2]
```diff
@@ -142,22 +142,33 @@ const StartPage: React.FC = () => {
...
-          );
-          return initialItem ? { ...item, data: initialItem.data } : null;
-        }),
-      )
-    : defaultBoardItem;
+  // TODO: Issue occurs when newly added items in new webui version are not saved in localStorage
+  // and thus not displayed on screen.
+  // Opted-out items should also be stored separately in localStorage, and newly added items
+  // should be included in initialBoardItems.
+  const boardItems = useMemo(() => {
```
Comment (nowgnuesLee) [inline react/src/pages/StartPage.tsx]: same as above

**Review by nowgnuesLee — CHANGES_REQUESTED** [review]

File: react/src/pages/DashboardPage.tsx (hunk 1 above)
Comment (ironAiken2) [reply react/src/pages/DashboardPage.tsx]: Thank you. Since the time complexity seems to be the same, I've modified it to make the code flow easier to understand.

**Review by yomybaby — APPROVED** [review]
LGTM
