### PR TITLE
fix: Unable to revoke shared folder permission and refactor the modify permissions modal.

### LINKED ISSUE #2545: Revoke shared folder permission doesn't working properly
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

24.09.0dev1

### Describe the bug

Revoking the access permission of shared folder from invited user doesn't work properly.

### To Reproduce

> ⚠️ NOTE: You need two user accounts (user A, user B) to test this issue. 

1. Login with user A account.
2. Go to Data & Storage menu.
3. Click `Share folder` icon button(Screenshot 2024-07-12 at 4 04 20 PM) in Controls column. 
4. Add user B email address with any permission.
5. Click `SHARE` button.
6. Logout user A account and login with user B account.
7. See invitation panel in Summary page.
8. Accept the invitation.
9. Logout user B account and login with user A account.
10. Go to Data & Storage menu again.
11. Click `Modify Permission` icon button (Screenshot 2024-07-12 at 4 07 08 PM) in Controls column.
12. Change the current permission to "kick out user".
13. Logout  user A account and login with user A account.
14. Go to Data & Storage menu.
15. See the error.

### Expected Behavior

When the permission per each shared folder has been changed to "kicked-out", then the invited user shouldn't be able to get access to the shared one.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by agatha197**
resolves #2545
related PR: https://github.com/lablup/backend.ai/pull/2731, https://github.com/lablup/backend.ai/pull/2740

### TL;DR

Fix a bug that changes the permissions of other people in the shared list.

### What changed?

- Updated the translation key for renaming a folder from 'data.folders.RenameAFolder' to 'data.explorer.RenameAFolder'.
- Refactored the permission modification logic to improve type safety and readability.
- Fixed a syntax error in the "Kick Out" list item by removing an extra quotation mark.

### How to test?
1. check out core branch to https://github.com/lablup/backend.ai/pull/2740, and cherry pick https://github.com/lablup/backend.ai/pull/2731 
2. Navigate to the storage list component.
3. Attempt to rename a folder and verify the correct translation is displayed.
4. Modify permissions for shared folders and ensure the changes are applied correctly.
5. Check that the "Kick Out" option in the permission dropdown works as expected.
6. Check the permission select has valid value just after accepting the invitation.

### Why make this change?

These changes improve the user experience by ensuring correct translations are used and enhance the reliability of permission management. The refactored code also improves maintainability and reduces potential bugs related to type mismatches.

### Screenshot
image
image
image

---

**Checklist:** (if applicable)

- [x] Mention to the original issue
- [ ] Documentation
- [x] Minium required manager version: 23.09
- [x] Specific setting for review (eg., KB link, endpoint or how to setup): refer [#2545](https://github.com/lablup/backend.ai-webui/issues/2545) 
- [x] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by agatha197** [comment]
* **#2644** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2644?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: src/components/backend-ai-storage-list.ts [hunk 1]
```diff
@@ -1098,29 +1098,46 @@ export default class BackendAiStorageList extends BackendAIPage {
...
-      if (response.length === 0) {
-        this.notification.text = _text('data.permission.NoChanges');
-      } else {
-        this.notification.text = _text('data.permission.PermissionModified');
-      }
-      this.notification.show();
-      this.modifyPermissionDialog.hide();
-    });
+    const leavePromiseArray = leaveList.map((input) =>
+      globalThis.backendaiclient.vfolder.leave(
```
Comment (yomybaby) [inline src/components/backend-ai-storage-list.ts]: Please check if the `/leave` API is for kicking out. I received an error message as follows:
```
{
    "type": "https://api.backend.ai/probs/insufficient-privilege",
    "title": "Insufficient privilege.",
    "msg": "Insufficient permission."
}
```

**Review by yomybaby — CHANGES_REQUESTED** [review]

**Review by gahyuun — APPROVED** [review]

**Review by yomybaby — APPROVED** [review]
LGTM
