### PR TITLE
fix(FR-1784): Replace popconfirm with Modal for image deletion

### LINKED ISSUE #4807: When deleting committed environment, all delete buttons switch to loading state.
webui version : 25.18.0-rc.1

{width=496}

JIRA Issue: FR-1784

### PR DESCRIPTION
**Pull request by nowgnuesLee**
resolves #4807 ([FR-1784](https://lablup.atlassian.net/browse/FR-1784))

This PR replaces the Popconfirm component with a BAIModal for deleting customized images in the CustomizedImageList component. The change improves the user experience by:

1. Using a proper modal dialog with an Alert component to warn users about the irreversible action
2. Improving the deletion flow by centralizing the deletion logic in the modal
3. Removing the `inFlightImageId` state in favor of tracking the image to delete with a dedicated state variable
4. Properly handling loading states during the deletion process

**Checklist:**

- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

[FR-1784]: https://lablup.atlassian.net/browse/FR-1784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by nowgnuesLee** [comment]
* **#4809** <a href="https://app.graphite.com/github/pr/lablup/backend.ai-webui/4809?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/lablup/backend.ai-webui/4809?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=4809).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: react/src/components/CustomizedImageList.tsx [hunk 1]
```diff
@@ -358,93 +360,15 @@ const CustomizedImageList: React.FC = () => {
...
-                (isInFlightForget || isInFlightUntag) &&
-                inFlightImageId === row?.id + customizedImageListFetchKey
-              }
-              disabled={
-                (isInFlightForget || isInFlightUntag) &&
-                inFlightImageId !== row?.id + customizedImageListFetchKey
-              }
-            />
-          </Popconfirm>
+            danger
```
Comment (ironAiken2) [inline react/src/components/CustomizedImageList.tsx]: You can use BAIButton with action to show loading indicator since confirm modal returns promise

File: react/src/components/CustomizedImageList.tsx [hunk 2]
```diff
@@ -518,6 +442,91 @@ const CustomizedImageList: React.FC = () => {
         columns={columns}
         hiddenColumnKeys={hiddenColumnKeys}
       />
+      <BAIModal
+        open={isDeleteModalOpen}
+        title={t('dialog.ask.DoYouWantToProceed')}
+        okText={t('button.Delete')}
```
Comment (ironAiken2) [inline react/src/components/CustomizedImageList.tsx:449]: How about displaying the committed image name, even if it's just briefly?

**Review by yomybaby — APPROVED** [review]
LGTM
