### PR TITLE
fix(FR-1100): image install doesn't work

### LINKED ISSUE #3798: image install doesn't work
follows #3756. Image installation doesn’t work due to changed structure.

JIRA Issue: FR-1100

### PR DESCRIPTION
**Pull request by agatha197**
Resolves #3798 ([FR-1100](https://lablup.atlassian.net/browse/FR-1100))

# Refactor Image Installation Process in ImageInstallModal

This PR refactors the image installation process in the `ImageInstallModal` component to improve code readability and maintainability. The changes include:

- Restructured the image resource configuration using the `SessionResources` interface
- Simplified image name construction with template literals
- Replaced imperative resource configuration with declarative approach using lodash utilities
- Improved GPU resource handling logic with cleaner conditional checks
- Enhanced resource slot compatibility checking

**Checklist:**

- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [x] Minimum requirements to check during review: Check you can download new image
- [ ] Test case(s) to demonstrate the difference of before/after

[FR-1100]: https://lablup.atlassian.net/browse/FR-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by nowgnuesLee — APPROVED** [review]
LGTM

**Review by lizable — APPROVED** [review]
Confirmed payload has been changed and works fine. LGTM.

**Review by yomybaby — CHANGES_REQUESTED** [review]
Please set `resource_opts.shmem` in session creation payload.

File: react/src/components/ImageInstallModal.tsx [hunk 1]
```diff
@@ -39,70 +42,82 @@ const ImageInstallModal: React.FC<ImageInstallModalInterface> = ({
...
+              'min',
+              1,
+            ) as number,
+            mem: mem || '320m', // 320m = addNumberWithUnits('256m', '64m')
+          },
+          resource_opts: {
+            shmem,
+          },
+        },
+      };
```
Comment (yomybaby) [inline react/src/components/ImageInstallModal.tsx]:
```suggestion
      const shmem = labels['ai.backend.resource.preferred.shmem'] || '64m';
      const mem =
        addNumberWithUnits(
          _.get(_.find(image?.resource_limits, { key: 'mem' }), 'min') ??
            '256m',
          shmem,
          'm',
        );

      const imageResource: SessionResources = {
        group_name: baiClient.current_group,
        domain: baiClient._config.domainName,
        type: 'batch',
        cluster_mode: 'single-node',
        cluster_size: 1,
        startupCommand: 'echo "Image is installed"',
        enqueueOnly: true,
        config: {
          resources: {
            ..._.mapValues(_.keyBy(image?.resource_limits, 'key'), 'min'),
            cpu: _.get(
              _.find(image?.resource_limits, { key: 'cpu' }),
              'min',
              1,
            ) as number,
            mem: mem
          },
          resource_opts: {
            shmem,
          },
        },
      };

```

**Review by yomybaby — CHANGES_REQUESTED** [review]
Please check this changes. There are duplicated fallback value handlings.
