### PR TITLE
fix(FR-1706): file list does not update when files have been updated

### LINKED ISSUE #4681: File list in File Explorer does not update when a file or folder has been uploaded.
JIRA Issue: FR-1706

### PR DESCRIPTION
**Pull request by nowgnuesLee**
resolves #4681 (FR-1706)

This PR makes several improvements to React hooks and fixes issues with file upload status tracking:

1. Refactors `useIntervalValue` and `useInterval` hooks to use `useEffectEvent` instead of `useRef` for better handling of callback functions
2. Fixes upload status tracking by removing hyphens from local IDs since Jotai atoms don't support hyphens in keys
3. Adds polling mechanism in `FolderExplorerModal` to update fetch key when there are pending uploads
4. Removes a console.log statement from `useDefaultSystemSSHImageWithFallback`

**Checklist:** (if applicable)

- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by nowgnuesLee** [comment]
* **#4682** <a href="https://app.graphite.com/github/pr/lablup/backend.ai-webui/4682?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/lablup/backend.ai-webui/4682?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=4682).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: react/src/components/FileUploadManager.tsx [hunk 1]
```diff
@@ -347,7 +347,7 @@ export const useFileUploadManager = (id?: string, folderName?: string) => {
   const setUploadRequests = useSetAtom(uploadRequestAtom);
 
   const [uploadStatus, setUploadStatus] = useUploadStatusAtomStatus(
-    id ? toLocalId(id) : '',
+    id ? toLocalId(id).replace(/-/g, '') : '', // since jotai atom does't use '-' in key, we need to replace it
```
Comment (agatha197) [inline react/src/components/FileUploadManager.tsx]:
```suggestion
    id ? toLocalId(id).replace(/-/g, '') : '', // since jotai atom doesn't use '-' in key, we need to replace it
```

**Review by agatha197 — CHANGES_REQUESTED** [review]
