### PR TITLE
fix: rewrite base class' attributeChangedCallback monitoring (#990)

### LINKED ISSUE #990: Reduce folder refresh calls to keep user query limit
**Describe the bug**

Many folder refresh call fired due to duplicate folder state management.

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:
1. Go to 'Data & Storage'
2. Open inspector and choose 'Network' pane
3. See increasing number / rate of list queries

**Expected behavior**
Stable / predictable queries

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.
가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.

**Client:**
 - OS: [e.g. macOS 10.14, Windows 10 (1903)]
 - App version: [e.g. 19.08.3] (if you are using a GUI client app)
 - Browser version: [e.g. Chrome 76, Safari, Edge] (if you are using a GUI web console)
 - Python version: [e.g. 3.7.4] (if you are using the Python SDK)
 - NodeJS version: [e.g. 12.0] (if you are using the Javascript SDK)

**Server:**
 - OS: macOS 11.3
   - Output of `uname -a`: [e.g. `Linux node01 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`]
 - Backend.AI version: 21.03.1
 - Python version: 3.9.5
 - Installation method: used scripts/install-dev.sh

**Additional context**

### PR DESCRIPTION
**Pull request by inureyes**
This PR resolves #990 
 * feat:  rewrite base class' attributeChangedCallback monitoring 
 * add: introduces atomic call check to folder refresh routine

### CODE REVIEW

File: src/components/backend-ai-storage-list.ts [hunk 1]
```diff
@@ -928,11 +930,12 @@ export default class BackendAiStorageList extends BackendAIPage {
     } else {
       this.shadowRoot.querySelector('vaadin-grid.folderlist').style.height = 'calc(100vh - 185px)';
     }
-    document.addEventListener('backend-ai-group-changed', (e) => this._refreshFolderList());
+    document.addEventListener('backend-ai-group-changed', (e) => this._refreshFolderList(true, 'group-changed'));
     document.addEventListener('backend-ai-ui-changed', (e) => this._refreshFolderUI(e));
     this._refreshFolderUI({'detail': {'mini-ui': globalThis.mini_ui}});
     // monkeypatch for height calculation.
     this.selectAreaHeight = this.shadowRoot.querySelector('#dropdown-area').offsetHeight ? this.shadowRoot.querySelector('#dropdown-area').offsetHeight : '56px';
+    this._triggerFolderListChanged();
```
Comment (lizable) [inline src/components/backend-ai-storage-list.ts:938]: I added this function [to initialize the storage status chart graph](https://github.com/lablup/backend.ai-webui/blob/554680e3bb85b4023f485ea9ff4420ad2ed3eddb/src/components/backend-ai-data-view.ts#L544-L547).

**Review by lizable — APPROVED** [review]
