### PR TITLE
fix(FR-366): remove unnecessary panel disabling via querySelector at vfolder invitation panel in summary view page

### LINKED ISSUE #3023: After whether accept/reject invitation of vfolder from another user(s), remaining invitation card disabled
When the user received more than one vfolder invitations and after accepting/rejecting one from list makes remaining invitation(s) card in “disabled” status. Here’s the video clip of how bug occurs.

!Screen Recording 2025-01-14 at 11.31.32 AM.mov|width=1882,height=1482,alt="Screen Recording 2025-01-14 at 11.31.32 AM.mov"!

JIRA Issue: FR-366

### PR DESCRIPTION
**Pull request by lizable**
resolves #3023 (FR-366)

Removes unnecessary UI element disabling when accepting or declining vfolder invitations. Previously, the code would disable the entire panel and all buttons when processing these actions, which was redundant since the operations are quick and the panel gets removed upon completion anyway.

Also fixes a typo in the method documentation ("vfloder" -> "vfolder").

1. Login with user A.
2. Create at least two vfolders if there's no vfolder created.
3. Invite user B with vfolders created in step 2 or that alreay exists.
4. Logout user A and Login with user B.
5. Go to `Summary` page.
6. See the Invitation panel.
7. Click Accept/Decline inside the panel.
8. Click another one in the panel.

**Checklist:**
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by lizable** [comment]
* **#3029** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3029?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3029?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=3029).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: src/components/backend-ai-summary-view.ts [hunk 1]
```diff
@@ -398,12 +398,7 @@ export default class BackendAISummary extends BackendAIPage {
...
     }
-    const panel = e.target.closest('lablup-activity-panel');
     try {
-      panel.setAttribute('disabled', 'true');
-      panel.querySelectorAll('mwc-button').forEach((btn) => {
-        btn.setAttribute('disabled', 'true');
-      });
       await globalThis.backendaiclient.vfolder.accept_invitation(invitation.id);
       this.notification.text =
         _text('summary.AcceptSharedVFolder') + `${invitation.vfolder_name}`;
```
Comment (yomybaby) [inline src/components/backend-ai-summary-view.ts:438]: <i class='graphite__hidden'>[Re: line +405]<br/><br/></i>

Let's add url to open vfolder explorer.
```gt_suggestion
      this.notification.url = `/data?tab=model&folder=${invitation.vfolder_id.replace('-','')}`;
      this.notification.show();
```



<span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3029?utm_source=unchanged-line-comment">Graphite</a>.</span>

**Review by yomybaby — CHANGES_REQUESTED** [review]
LGTM. However, I suggest adding a link for the "Open Folder" feature.

**Review by agatha197 — APPROVED** [review]
I agree with Jongeun's suggestion and checked it works well.

**Comment by lizable** [comment]
I applied it. It would be look like this:

**Review by yomybaby — APPROVED** [review]
LGTM!
