### PR TITLE
fix(FR-630): Support modifying resource preset using id

### LINKED ISSUE #3319: failed to modify resource preset
failed to modify resource preset.

id of type ‘UUID’ is required, but it was not provided

!스크린샷 2025-03-06 오후 3.46.47.png|width=653,height=717,alt="스크린샷 2025-03-06 오후 3.46.47.png"!

JIRA Issue: FR-630

### PR DESCRIPTION
**Pull request by nowgnuesLee**
resolves #3319 (FR-630)

Starting from this PR, resource preset updates will be made using the `id` instead of `name`, following the core `version 25.4.0`

**changes**
* there are two type of modify commit, `ResourcePresetSettingModalModifyByIdMutation` and `ResourcePresetSettingModalModifyByNameMutation`.

**Checklist:** (if applicable)

- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by nowgnuesLee** [comment]
* **#3318** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3318?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3318?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=3318).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: react/src/components/ResourcePresetSettingModal.tsx [hunk 1]
```diff
@@ -121,30 +141,60 @@ const ResourcePresetSettingModal: React.FC<ResourcePresetSettingModalProps> = ({
...
-                onRequestClose(true);
-              }
-            },
-            onError(err) {
-              message.error(err?.message);
-            },
-          });
+          if (
+            resourcePreset.id &&
+            baiClient.isManagerVersionCompatibleWith('25.4.0')
```
Comment (ironAiken2) [inline react/src/components/ResourcePresetSettingModal.tsx]: We use the `updateSupportList` in esm file to show which features work for a particular version.

https://github.com/lablup/backend.ai-webui/blob/d4d8cce1ab501b2eb4fa03429dce20f4f37b4d5b/src/lib/backend.ai-client-esm.ts#L627

Comment (ironAiken2) [reply react/src/components/ResourcePresetSettingModal.tsx]: And also, id field is  checked via @since in the gql schema as of version 25.4.0, so I think this part can be deleted.

**Review by ironAiken2 — CHANGES_REQUESTED** [review]
I left few comments :)

**Comment by nowgnuesLee** [comment]
I accidentally created a new PR while working with Lock Graphite. I have closed the PR, so you can ignore it. Sorry about that!

**Review by ironAiken2 — APPROVED** [review]
LGTM

**Comment by lizable** [comment]
Works fine in `25.4.0`. LGTM.

**Review by lizable — APPROVED** [review]
Works fine in `25.4.0`. LGTM.
