### PR TITLE
fix: Replace the link detail view in the Web Terminal Guide with the correct url

### LINKED ISSUE #961: Learn more link in Web terminal guide is broken.
**Describe the bug**
문제가 발생하는 상황에 대한 요약 설명을 적어주세요.
When the user clicks Learn more link in the dialog pops up right after executing web terminal in the session,
It directs to the wrong link.

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:
1. Go to 'Sessions' page.
2. Click on 'START' button.
3. 'Session Launcher' dialog pops up.
4. Scroll down to bottom and click 'LAUNCH' button.
5. Click terminal icon button in the control tab of the session just created in step 4.
6. 'Advanced Web Terminal Usage: Copy terminal contents ' dialog pops up.
7. Click right button``>`` until the last page comes.
8. Click 'Learn more' link.
9. See the error.

**Expected behavior**
원래 기대했던 동작은 어떤 것인지 명확하게 적어주세요.
the link should directs to the [right page](https://console.docs.backend.ai/en/latest/sessions_all/sessions_all.html#copy-terminal-contents).

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.
가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.

image

### PR DESCRIPTION
**Pull request by Sujin-Kim1**
this closes #961

### CODE REVIEW

File: src/components/backend-ai-app-launcher.ts [hunk 1]
```diff
@@ -919,7 +919,7 @@ export default class BackendAiAppLauncher extends BackendAIPage {
           </span>
           <div class="flex layout center-justified vertical center">
             <p>${_text('webTerminalUsageGuide.CopyGuideFour')}</p>
-            <a href="https://console.docs.backend.ai/${lang}/latest/session_use/session_use.html#advanced-web-terminal-usage"
+            <a href="https://console.docs.backend.ai/${lang}/latest/sessions_all/sessions_all.html#copy-terminal-contents"
```
Comment (lizable) [inline src/components/backend-ai-app-launcher.ts]: Let's show advanced-web-terminal-usage instead of copying terminal contents, since It covers more detail.

**Review by lizable — CHANGES_REQUESTED** [review]
And also I found some strange carousel page changing event occurs when opening web terminal application right after page refreshing. I would like you to check this out and fix this as well.

https://user-images.githubusercontent.com/46954439/118217499-6f11dd80-b42a-11eb-9c63-2c1cb70bade3.mov

**Review by lizable — APPROVED** [review]
LGTM
