### PR TITLE
fix(FR-727): Modify ChatSender's style to follow Antd's design system

### LINKED ISSUE #3419: Dark mode is not applied to the ChatSender component

### PR DESCRIPTION
**Pull request by nowgnuesLee**
resolves #3419 (FR-727)
This PR resolves dark mode bug in the `ChatSender` component.

**changes**
* remove the `background` style to enable dark mode
* remove unnecessary `border-radius` style

|before|after|
|------|-----|
| |  |

**Checklist:** (if applicable)

- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

File: react/src/components/Chat/ChatInput.tsx [hunk 1]
```diff
@@ -44,9 +44,7 @@ const ChatInput: React.FC<ChatInputProps> = ({
   const { token } = theme.useToken();
 
   const ChatInputStyle = {
-    background: '#ffffff',
-    borderTop: '1px solid #f0f0f0',
-    borderRadius: '0 0 8px 8px',
```
Comment (ragingwind) [inline react/src/components/Chat/ChatInput.tsx:49]: Why removed radius too?

Comment (yomybaby) [reply react/src/components/Chat/ChatInput.tsx:49]: If borderRadius revert needed, please use `token.borderRadiusLG`. It's default value is `8`. Don't forget to put the `px` when using token in `css`. `${token.borderRadiusLG}px`

Comment (ragingwind) [reply react/src/components/Chat/ChatInput.tsx:49]: It was moved from origin style (sorry that I couldn't find where was). It can be kept removed If you think it was unnecessary. It's not a big deal.

Comment (nowgnuesLee) [reply react/src/components/Chat/ChatInput.tsx:49]: Thank you! I removed it because it doesn't affect the UI. But if you notice anything strange, feel free to let me know.

**Review by ragingwind — APPROVED** [review]

**Review by yomybaby — APPROVED** [review]
LGTM
